#ASP.NET Core
#Build and test ASP.NET Core projects tergeting .NET Core.
#Add steps that run test, create a NuGet package, deploy, and more:
trigger:
- main
pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'